// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcvbsbiqcphrendiwcdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjdmJzYmlxY3BocmVuZGl3Y2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTE1ODMsImV4cCI6MjA3MzkyNzU4M30.HzPc8u-b1griOqk4t38LAvGb43Hw9c9uVHrng9kPhls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});